server:
  port: 8081

spring:
  application:
    name: restaurant-api
  datasource:
    url: jdbc:postgresql://restaurant-api-postgres:5432/restaurant_api
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
