server:
  port: 8082

spring:
  application:
    name: restaurant-api
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_api
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
