server:
  port: 8080

spring:
  application:
    name: order-api
  elasticsearch:
    uris: ${ELASTICSEARCH_HOST:http://localhost}:${ELASTICSEARCH_PORT:9200}
    username:
    password:
    connection-timeout: 10s
    socket-timeout: 30s

restaurant:
  api:
    url: http://localhost:8081/api

delivery:
  api:
    url: http://localhost:8082/api/delivery
